# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
general:
  branches:
    only:
#    - master # list of branches to build
#    - /feature-.*/ # or regexes
    - circleCI-machine # list of branches to build
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:latest
    # specify the version you desire here
#    - image: maven:3.5.2-jdk-8
      cmd: ["/bin/bash"]
#    parallelism: 4

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx2048m

    steps:
    - checkout

    # Download and cache dependencies
#    - restore_cache:
#        keys:
#        - v1-dependencies-{{ checksum "pom.xml" }}
#        # fallback to using the latest cache if no exact match is found
#        - v1-dependencies-
#
#    - run: mvn dependency:go-offline
#
#    - save_cache:
#        paths:
#        - ~/.m2
#        key: v1-dependencies-{{ checksum "pom.xml" }}

    # run tests!
#    - run: mvn install
# memory limitations   - run: mvn install -Drat.skip=false -Dlicense.skip=false -DexcludedGroups="org.apache.drill.categories.SlowTest,org.apache.drill.categories.UnlikelyTest,org.apache.drill.categories.SecurityTest" -DmemoryMb=1500 -DdirectMemoryMb=2500 -Ptravis
    - run: mvn install -Drat.skip=false -Dlicense.skip=false -DexcludedGroups="org.apache.drill.categories.SlowTest,org.apache.drill.categories.UnlikelyTest,org.apache.drill.categories.SecurityTest" -Ptravis
